#############################################################################
# Makefile for building: Tcoin-qt
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? ?? 8 17:23:05 2014
# Project:  bitcoin-qt.pro
# Template: app
# Command: c:\Qt\4.8.5\bin\qmake.exe USE_UPNP=- -o Makefile bitcoin-qt.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.8.5\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: bitcoin-qt.pro  ../Qt/4.8.5/mkspecs/win32-g++/qmake.conf ../Qt/4.8.5/mkspecs/features/device_config.prf \
		../Qt/4.8.5/mkspecs/qconfig.pri \
		../Qt/4.8.5/mkspecs/features/qt_functions.prf \
		../Qt/4.8.5/mkspecs/features/qt_config.prf \
		../Qt/4.8.5/mkspecs/features/exclusive_builds.prf \
		../Qt/4.8.5/mkspecs/features/default_pre.prf \
		../Qt/4.8.5/mkspecs/features/win32/default_pre.prf \
		../Qt/4.8.5/mkspecs/features/debug.prf \
		../Qt/4.8.5/mkspecs/features/debug_and_release.prf \
		../Qt/4.8.5/mkspecs/features/default_post.prf \
		../Qt/4.8.5/mkspecs/features/win32/default_post.prf \
		../Qt/4.8.5/mkspecs/features/win32/thread.prf \
		../Qt/4.8.5/mkspecs/features/win32/rtti.prf \
		../Qt/4.8.5/mkspecs/features/win32/exceptions.prf \
		../Qt/4.8.5/mkspecs/features/win32/stl.prf \
		../Qt/4.8.5/mkspecs/features/static.prf \
		../Qt/4.8.5/mkspecs/features/warn_on.prf \
		../Qt/4.8.5/mkspecs/features/qt.prf \
		../Qt/4.8.5/mkspecs/features/moc.prf \
		../Qt/4.8.5/mkspecs/features/win32/windows.prf \
		../Qt/4.8.5/mkspecs/features/resources.prf \
		../Qt/4.8.5/mkspecs/features/uic.prf \
		../Qt/4.8.5/mkspecs/features/yacc.prf \
		../Qt/4.8.5/mkspecs/features/lex.prf \
		c:/Qt/4.8.5/lib/qtmaind.prl \
		c:/Qt/4.8.5/lib/QtGui.prl \
		c:/Qt/4.8.5/lib/QtNetwork.prl \
		c:/Qt/4.8.5/lib/QtCore.prl
	$(QMAKE) USE_UPNP=- -o Makefile bitcoin-qt.pro
..\Qt\4.8.5\mkspecs\features\device_config.prf:
..\Qt\4.8.5\mkspecs\qconfig.pri:
..\Qt\4.8.5\mkspecs\features\qt_functions.prf:
..\Qt\4.8.5\mkspecs\features\qt_config.prf:
..\Qt\4.8.5\mkspecs\features\exclusive_builds.prf:
..\Qt\4.8.5\mkspecs\features\default_pre.prf:
..\Qt\4.8.5\mkspecs\features\win32\default_pre.prf:
..\Qt\4.8.5\mkspecs\features\debug.prf:
..\Qt\4.8.5\mkspecs\features\debug_and_release.prf:
..\Qt\4.8.5\mkspecs\features\default_post.prf:
..\Qt\4.8.5\mkspecs\features\win32\default_post.prf:
..\Qt\4.8.5\mkspecs\features\win32\thread.prf:
..\Qt\4.8.5\mkspecs\features\win32\rtti.prf:
..\Qt\4.8.5\mkspecs\features\win32\exceptions.prf:
..\Qt\4.8.5\mkspecs\features\win32\stl.prf:
..\Qt\4.8.5\mkspecs\features\static.prf:
..\Qt\4.8.5\mkspecs\features\warn_on.prf:
..\Qt\4.8.5\mkspecs\features\qt.prf:
..\Qt\4.8.5\mkspecs\features\moc.prf:
..\Qt\4.8.5\mkspecs\features\win32\windows.prf:
..\Qt\4.8.5\mkspecs\features\resources.prf:
..\Qt\4.8.5\mkspecs\features\uic.prf:
..\Qt\4.8.5\mkspecs\features\yacc.prf:
..\Qt\4.8.5\mkspecs\features\lex.prf:
c:\Qt\4.8.5\lib\qtmaind.prl:
c:\Qt\4.8.5\lib\QtGui.prl:
c:\Qt\4.8.5\lib\QtNetwork.prl:
c:\Qt\4.8.5\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) USE_UPNP=- -o Makefile bitcoin-qt.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) C:/Users/kennhu/Documents/GitHub/Tcoin/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/Users/kennhu/Documents/GitHub/Tcoin/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) $(MAKE)
	-$(DEL_FILE) clean
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

C:/Users/kennhu/Documents/GitHub/Tcoin/src/leveldb/libleveldb.a: FORCE
	cd C:/Users/kennhu/Documents/GitHub/Tcoin/src/leveldb && CC=gcc CXX=g++ TARGET_OS=OS_WINDOWS_CROSSCOMPILE $(MAKE) OPT="-pipe -D_FORTIFY_SOURCE=2 -O2" libleveldb.a libmemenv.a && ranlib C:/Users/kennhu/Documents/GitHub/Tcoin/src/leveldb/libleveldb.a && ranlib C:/Users/kennhu/Documents/GitHub/Tcoin/src/leveldb/libmemenv.a

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
